### ISSUE TITLE
Guest Checkout order.emailaddress

### ISSUE THREAD

**Issue by inelukipg** [magepal/magento2-google-tag-manager#30]
Hi,
I'm using guest checkout (1-page) so customer variables are not created since the customers are not logged in on checkout page.

Is it possible to fecth `order.emailaddress` or something that's customer specific to the datalayer at checkout.

It's a affiliate program that needs the customers email address encrypted in md5 to cross detect users between devices.

**Comment by srenon** [comment]
This is not a feature that I'm going to build into the core module since it will contain a hash of user email.

You could either rewrite or create and "after" plugin to add that feature in
MagePal\GoogleTagManager\Model\Order::getOrderLayer()

If you want to open paid support ticket so that someone can build that feature for you email support@magepal.com.
