### ISSUE TITLE
What about GDPR?

### ISSUE THREAD

**Issue by gediminaskv** [magepal/magento2-google-tag-manager#42]
It would be great to have a feature like if cookie consent isn't given GTM wouldn't start.

**Comment by srenon** [comment]
@gediminaskv .... could you provide more information?

Are you referring to build a "cookie consent" feature or using a third party? 

If you have a feature like this then your reporting will be off because on first visit GTM would no load until after the user accept the cookie so your average time on page, page load time and a lot of other things will be off

**Comment by gediminaskv** [comment]
@srenon Yes, I am refering to Magento build in cookie consent feature. For instance, if one is using GTM for Google Analytics? GA uses cookies and it is 3rd party cookies which need consent as I understand http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

Features would be off, but it's the EU law which business must apply if they customers are in EU.

**Comment by srenon** [comment]
Originally this was included but was causing few issues ... see https://github.com/magepal/magento2-google-tag-manager/issues/11

If you take a look at Magento 2.2.5, all this was refactored and need to be done in Javascript because of FPC.

I will need to do some refactoring to add this feature.

Since GTM on its own just store data and does not track users, should GTM stop sending data or should it send a do not track flag and GTM integration check for it?

**Comment by gediminaskv** [comment]
I think I found a solution without modifying the extension. It is done through GTM itself. Here is my tutorial:

### How to be GDPR compliant using Google Tag Manager and Magento 2

1. Create a "1st Party Cookie" variable with "user_allowed_save_cookie" cookie name, which is Magento cookie consent. You may tick "URI-decode cookie". https://prnt.sc/l1lh0p
2. Create a "Page View" trigger to prompt only when our previous variable equals "undefined" https://prnt.sc/l1lh88
3. Go to "Tags" and edit a tag which you want to bound with Magento cookie consent and add exception of recently created trigger. https://prnt.sc/l1lhem

I have put Google Analytics code in GTM, not on Magento. So in my case GTM won't allow to inject Google Analytics code except cookie consent is given.

**Comment by stevensagaar** [comment]
We had a similar issue and we purchased the following extension which worked perfect for us with cookie consent.

[Magento 2 Google Tag Manager with GDPR compatible](https://www.scommerce-mage.com/magento-2-google-tag-manager-enhanced-ecommerce-tracking.html)

**Comment by simonmaass** [comment]
just created a pull request that adds this functionality... feel free to use

**Comment by srenon** [comment]
@gediminaskv ... please take a look at the new release and let me know your thoughts
