### ISSUE TITLE
Data Layer Only Mode

### ISSUE THREAD

**Issue by adamlytics** [magepal/magento2-google-tag-manager#55]
#### Magento version #:
any
#### Edition (EE, CE, OS, etc):
any
#### Expected behavior:
It would be great to be able to use this extension for the data layer only, meaning the GTM library is optional.  It would still create and push to the data layer as normal, allowing another tag manager or library to utilize the data layer.
#### Actual behavior:
GTM is required
#### Steps to reproduce:
n/a

**Comment by srenon** [comment]
@adamlytics ... Let me think about this since it could increase our support request by users disabling it and then contacting us to say the extension does not work... 

To accomplish your goal all you would need to do is comment out this line (you could use composer patch).

https://github.com/magepal/magento2-google-tag-manager/blob/master/view/frontend/web/js/datalayer.js#L110
