### ISSUE TITLE
No compatibility with MagePal_EnhancedEcommerce

### ISSUE THREAD

**Issue by evilprophet** [magepal/magento2-google-tag-manager#62]
#### Expected behavior:
The test will be correctly executed. The error won't be thrown.

#### Actual behavior:
On version 2.4.0 during executing, test error is thrown.
Magento\Framework\Exception\RuntimeException: Type Error occurred when creating object: MagePal\EnhancedEcommerce\Block\Data\Product\Interceptor

#### Note
The problem does not appear on version 2.3.1

**Comment by srenon** [comment]
@evilprophet.... Sorry about this, but in order to add new features and create the best extension without overcomplicating it from time to time we will need to break compatibility with a previous version even though we try our best to limit this as much as possible.

We are busy working on our private composer server which will address this issue shortly

![image](https://user-images.githubusercontent.com/1415141/69881690-c7d3d180-129b-11ea-9861-127b376674b7.png)

Once again sorry for the inconvenience, please log in to your MagePal account to download the latest version which is free to all users.

**Comment by evilprophet** [comment]
@evilprophet Thanks for the information, I didn't notice it before... :)
